### ISSUE TITLE
CMS Default Features

### ISSUE THREAD

**Issue by tbaustin** [escaladesports/escalade#394] opened 2019-10-22 14:02 UTC
CMS needs to have a bunch of stuff out of the box (was talked about in the meeting). @MastaAaron  can you put the notes you took here. Try to make each one into a well defined task!

**Comment by MastaAaron** [comment] 2019-10-26 00:45
**FYI to everyone: this isn't quite done yet. Still have just a bit more to add regarding products...**

---

# Wanted CMS Functionality & Ideas

### Products
- Multiple/batch image upload
  - Should at least be possible with [Sanity's API endpoints for assets](https://www.sanity.io/docs/http-api-assets)
  - See the concerns down in [Question Marks](#question-marks)
- Start a new collection item as a duplicate of existing
  - Would allow easier entry of variants that share a lot of field values w/ a parent
  - Depends on Sanity's limitations & level of customization
- Ability to assign a product to multiple categories
- Nitpick: make currency inputs WAY less sensitive to the scroll wheel (or get rid of scroll wheel interaction altogether)


### Pages/Templates
- Image size customizations **via CMS**
  - Dimensions-based (i.e. exact width/height)
  - Ratio-based (i.e. specify aspect ratio along w/ percent or exact width)
  - Not sure how this would affect/be affected by the concerns below in [Question Marks](#question-marks)
- Ability to add videos within page content
- Home page carousel – ability to schedule start/end dates for new slides being visible on site
- **IDEA:** Have a system of page widgets
  - Like what we're doing on [Onix](https://github.com/escaladesports/onixpickleball.com), but a little more sophisticated
  - Identify the most basic/versatile layout widgets that could be used on any site & have these in the CMS by default
  - How the site actually implements/styles the layout would vary from site to site
  - This would help follow a CMS-first approach to building sites – i.e. we evaluate mockups from Creative in terms of how they could be built w/ CMS widgets
- Custom HTML inputs on each page/template, including ability to inject custom style tags
  - This would probably have to be rendered in a designated area of each page before/after all the page widgets
  - Custom scripts no longer needed; Google Tag Manager handles this already
- **IDEA:** Templates for products/categories/etc.
  - All templates for a site would be fully built out with the widget system described above and could theoretically be totally changed via the CMS
  - Each product/category/other entity has a template selected (different entities default to different templates)
  - Some widgets would have to be pretty use-case-specific (e.g. "Add to Cart" button & sections on product template that actually use & display product data); but these should still be available as widgets even if they have limited customization options
    - This way, a CMS user could theoretically create their own alternate product template by reusing the product-specific widgets and building the rest of the template around them differently
- **NOTE:** Much of this seems like it would benefit greatly from Sanity's system/philosophy of [portable text](https://www.sanity.io/guides/introduction-to-portable-text)


### SEO/Other
- Ability to display rich snippets in Google search results
- Ability to set custom HTML `id` attributes on `<a>` tags within navbar/dropdowns
  - Could just be another field in custom navigation


# Question Marks

### Double entry of product information
We should ideally avoid this. All the CMS users (esp. the Matts) have indicated repeatedly that this is a huge pain point/time waster for them.

Perhaps basic product info could be entered in Salsify (or the AS400, which syncs to Salsify) once and then synced to the CMS. After some digging, it looks like it may actually be feasible to do this:
  - A custom [product change/create webhook](https://developers.salsify.com/docs/webhooks-prod-change) could be set up in Salsify – according to Jason, we should be able to use different webhooks for products on different sites/brands
  - Products could be programmatically added to the CMS with [Sanity's API](https://www.sanity.io/docs/http-mutations)

Only the ID and other basic product data would be synced. Any site-specific information or data that can't be stored in Salsify (like attributes/options/variants) can just be entered later in the CMS after sync. Maybe new products could be synced to the CMS with an inactive status set by default, and then users would activate them gradually as they fill in the remaining info in the CMS.

Of course, we would need to consult our CMS users again about this idea to get their thoughts

### Product images – Salsify?
This goes hand-in-hand with above. To avoid double-upload of product images, maybe Salsify could just be the source of truth.

To Jason's point during conversations he and I have had, Salsify should have every type of product image we could ever need in terms of content of the images – it just doesn't have the resizing/transformation tools we like.

That said, it should technically be possible sync *images* as well. When products in Salsify are updated with images, a webhook could potentially grab the ecomm-relevant images we need and [bulk-upload them to Sanity with the assets API](https://www.sanity.io/docs/http-api-assets). From there, I assume we could fetch images from Sanity & apply transformations like normal.

If we end up not wanting our images in Sanity, just swap it out for whatever we use – the webhook approach should still work, I think.

**Comment by MastaAaron** [comment] 2019-10-29 22:26
Closing here and opening as an issue in the [projects](https://github.com/escaladesports/projects/issues/8) repo, as this may not end up being the most appropriate place due to potential restructuring of our repos.

**Closed by MastaAaron** 2019-10-29 22:26 UTC
